SECRET_KEY = 'you-will-never-guess'
DEBUG=True
MONGODB_DB = 'flaskbook'
HOSTNAME = 'https://127.0.0.1'
UPLOAD_FOLDER = '/home/rick/projects/flaskbook/static/images'
STATIC_IMAGE_URL = 'images'
AWS_BUCKET = ''
AWS_CONTENT_URL = ''
AWS_SEND_MAIL = True
RECAPTCHA_PUBLIC_KEY = 'Your Data here'
RECAPTCHA_PRIVATE_KEY = 'Your Data here'
